env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: off
  max-len: ["error", 120, 4]
  semi: ["error", "never"]
